Repository teia-community/teia-ui, pull requests merged in 2022-08, with the labels that each got.

#136 [feat] ⚡ add IPFS proxy support
  .env
  src/data/ipfs.js
Labels: 💪 enhancement, 🛠 developer, ⛏ minting / ipfs

#154 fix: ⚡️ formats with no cover
  src/data/ipfs.js
Labels: Priority: Critical

#169 fix: ⚡️ 0ꜩ swaps
  src/context/HicetnuncContext.js
  src/pages/objkt-display/tabs/swap.js
Labels: 🐛 bug
