Repository teia-community/teia-ui, pull requests merged in 2022-03, with the labels that each got.

#30 fixed swapping in collab mode
  src/context/HicetnuncContext.js
Labels: 🤜 🤛 collab-contract

#35 Update texts
  CODE_OF_CONDUCT.md
  public/languages/en.json
  public/languages/pt.json
  src/components/header/index.js
  src/pages/about/index.js
  src/pages/objkt-display/tabs/swap.js
Labels: ✍️ copyright

#47 fix: 🔥 add back the interactive symbol
  craco.config.js
  src/components/media-types/html/index.js
  src/icons/generative.js
  src/icons/minted.js
  src/icons/swap.js
  src/icons/trade.js
  src/pages/display/index.js
  src/pages/friends/index.js
  src/pages/objkt-display/tabs/history.js
  src/pages/search/index.js
  src/utils/with-icon.js
Labels: 💅 styling
