Repository teia-community/teia-ui, pull requests merged in 2022-07, with the labels that each got.

#117 fix: ⚡️ prevent restricted swaps from being the main swap
  src/components/item-info/index.js
  src/pages/objkt-display/index.js
Labels: 🐛 bug

#113 feat: ⚡️ minting metadata improvements (Metadatas + UI)
  package-lock.json
  package.json
  src/components/collab/create/BeneficiaryRow.js
  src/components/collab/create/CollaboratorRow.js
  src/components/collab/show/TxRow.js
  src/components/input/index.js
  src/components/input/styles.module.scss
  src/components/layout/page/styles.module.scss
  src/components/preview/index.js
  src/components/preview/styles.module.scss
  src/components/select/index.js
  src/components/select/styles.module.scss
  src/constants.js
  src/data/ipfs.js
  src/pages/config/index.js
  src/pages/mint/index.js
  src/pages/mint/styles.module.scss
  src/pages/search/index.js
Labels: 💪 enhancement, 💅 styling, ⛏ minting / ipfs

#125 fix: ⚡️ husky on windows
  .husky/pre-commit
Labels: 🛠 developer

#126 feat: 💄 modernize the github templates
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 📖 documentation, 💪 enhancement

#138 fix: ⚡️ use unreleased spec keys 🙈
  src/data/ipfs.js
  src/pages/mint/index.js
Labels: ⛏ minting / ipfs
